"""
Agent State module.
Defines the schema for the state object passed between nodes in the LangGraph.
"""

from typing import TypedDict, List, Optional, Annotated
from langchain_core.messages import BaseMessage
import operator

class AgentState(TypedDict):
    """
    Represents the state of the Study Coach agent at any given point in the graph.
    """
    # List of messages in the current turn (Annotated with operator.add to append new messages)
    messages: Annotated[List[BaseMessage], operator.add]
    
    # Raw input data for the student (scores, habits, etc.)
    student_data: dict
    
    # List of identified weak areas (e.g., 'math', 'attendance')
    learning_gaps: List[str]
    
    # The 7-day study plan generated by the PlannerNode
    study_plan: Optional[str]
    
    # Study tips retrieved from the RAG knowledge base
    retrieved_resources: List[str]
    
    # External resources/links retrieved from the WebSearchTool
    web_links: List[str]
    
    # Full conversation history for context (role/content format)
    session_history: List[dict]
    
    # Flag to determine if the query is academic or general conversation
    is_study_query: bool

